config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/calendar', to: 'static_pages#calendar'
  get '/weather', to: 'static_pages#weather'

  resources :funerals
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/funeral.rb
class Funeral < ApplicationRecord
  validates :name, presence: true, length: { maximum: 140 }
  before_save :set_end_time
  validates :start_time, :end_time, :overlap => { :exclude_edges => ["start_time", "end_time"] }

  def set_end_time
    self.end_time = self.start_time + 2.hours
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_customer
    unless logged_in?
      flash[:danger] = 'Please log in'
      redirect_to login_url
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in_customer, only: :index

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = "#{@customer.name} created."
      log_in(@customer)
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :password)
  end
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  before_action :set_funeral, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_customer

  def index
    @funerals = Funeral
      .where('start_time > ?', params[:date])
      .where('end_time < ?', Date.parse(params[:date]).end_of_day)

    @weather = WeatherService.new(params[:date]).weather
  end

  def show
  end

  def new
    @funeral = Funeral.new
  end

  def edit
  end

  def create
    @funeral = Funeral.new(funeral_params)

    respond_to do |format|
      if @funeral.save
        format.html { redirect_to @funeral, notice: 'Funeral was successfully created.' }
        format.json { render :show, status: :created, location: @funeral }
      else
        format.html { render :new }
        format.json { render json: @funeral.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @funeral.update(funeral_params)
        format.html { redirect_to :back, notice: 'Funeral was successfully updated.' }
        format.json { render :show, status: :ok, location: @funeral }
      else
        format.html { render :edit }
        format.json { render json: @funeral.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @funeral.destroy
    redirect_to :back
  end


  def redirect_back
    redirect_to :back
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funeral
      @funeral = Funeral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funeral_params
      params.require(:funeral).permit(:name, :start_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    customer = Customer.find_by(email: params[:session][:email].downcase)
    if customer && customer.authenticate(params[:session][:password])
      log_in customer
      redirect_to static_pages_home_path
    else
      flash.now[:notice] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_customer, only: [:calendar, :weather, :reservation]

  def home
  end

  def calendar
  end

  def weather
    @weather = WeatherService.new(Date.today.to_s).weather
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/funerals_helper.rb
module FuneralsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(customer)
    session[:customer_id] = customer.id
  end

  def current_customer
    @current_customer ||= Customer.find_by(id: session[:customer_id])
  end

  def current_customer?(customer)
    customer == current_customer
  end

  def logged_in?
    !current_customer.nil?
  end

  def log_out
    session.delete(:customer_id)
    @current_customer = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/customers/index.html.erb
<% provide(:title, 'Customers') %>
<h1>All Customers</h1>

<% @customers.each do |c| %>
  <p><%= c.name %></p>
  <p><%= c.email %></p>
  <br><br>
<% end %>

app/views/customers/new.html.erb
<% provide(:title, 'Register') %>
<h1>New Customer</h1>

<%= form_for @customer do |f| %>
  <% if @customer.errors.any? %>
    <h3><%= pluralize(@customer.errors.count, 'error') %>:</h3>
    <ul>
    <% @customer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit 'Create account' %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/funerals/_form.html.erb
<%= form_for(funeral) do |f| %>
  <% if funeral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funeral.errors.count, "error") %> prohibited this funeral from being saved:</h2>

      <ul>
      <% funeral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funerals/edit.html.erb
<h1>Editing Funeral</h1>

<%= render 'form', funeral: @funeral %>

<%= link_to 'Show', @funeral %>

app/views/funerals/index.html.erb
<% provide(:title, 'Funerals') %>
<p id="notice"><%= notice %></p>

<h1>Funerals</h1>

<% unless @weather.nil? %>
<h3>Weather:</h3>
  Temperature:
  <%= @weather['main']['temp'] %><br>
  <%= @weather['weather'].first['description'] %>
<% else %>
  <h3>There is no weather forecast for <%= params[:date] %>.</h3>
<% end %>

<% if @funerals.empty? %>
  <h3>There are currently no funerals reserved for <%= params[:date] %>.</h3>
  You can <%= link_to 'create', new_funeral_path %> an appointment.
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Start time</th>
        <th>End time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @funerals.each do |funeral| %>
        <tr>
          <td><%= funeral.name %></td>
          <td><%= funeral.start_time %></td>
          <td><%= funeral.end_time %></td>
          <td><%= link_to 'Show', funeral %></td>
          <td><%= link_to 'Edit', edit_funeral_path(funeral) %></td>
          <td><%= link_to 'Destroy', funeral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Funeral', new_funeral_path %>
<% end %>

app/views/funerals/new.html.erb
<% provide(:title, 'Reservationr') %>
<h1>New Funeral</h1>

<%= render 'form', funeral: @funeral %>

app/views/funerals/show.html.erb
<% provide(:title, 'Funeral') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @funeral.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @funeral.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @funeral.end_time %>
</p>

<%= link_to 'Edit', edit_funeral_path(@funeral) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | CatFuneral</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', static_pages_home_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Customers', customers_path %></li>
          <li><%= link_to 'Reservation', new_funeral_path %></li>
          <li><%= link_to 'Weather', weather_path %></li>
          <li><%= link_to 'Calendar', calendar_path %></li>
          <li><%= link_to 'Logout', '/logout', method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Sign up', new_customer_path %></li>
        <% end %>
      </ul>
    <%= yield %>
  </body>
</html>

app/views/static_pages/calendar.html.erb
<% provide(:title, 'Calendar') %>
<h1>Calendar</h1>
<%= month_calendar do |date| %>
  <%= link_to date, funerals_path(date: date) %>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<h1>FuneralCat Home</h1>
<p>Cat funeral app.</p>

app/views/static_pages/weather.html.erb
<% provide(:title, 'Weather') %>
<h1>Weather Today</h1>

Weather: <%= @weather['weather'].first['description'] %><br>
Temperature: <%= @weather['main']['temp'] %> C<br><br><br>